export const blogs = [
  {
    id: "1",
    image: "https://toplistsaigon.com/wp-content/uploads/2019/09/nha-hang-do-nuong-o-sai-gon-9.jpg",
    banner: "https://thegoldenspoon.com.vn/wp-content/uploads/2020/06/GG1Ty-bo-online_App-840-480-1.png",
    title: "Thể lệ chương trình: Ăn GoGi, Cơ Hội Trúng 1 Tỷ",
    content: [
      "<p>Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé: </p>",
      "<p> NHẬN NGAY VOUCHER 100K ÁP DỤNG CHO HÓA ĐƠN 400K NGAY KHI BẤM ĐỔI ƯU ĐÃI VỚI 0 G COINT</p>",
      "Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé:",
      "<p>🔶 Sử dụng ưu đãi tại GoGi và nhận ngay chiếc mã QR code kì diệu để tham gia quay thưởng với tổng giá trị tiền mặt 1 Tỷ Đồng trong vòng 10 tuần liên tiếp.</p>",
      "<p>🔶 Theo dõi và tham gia minigame trên livestream quay thưởng 1 Tỷ Đồng lúc 21:00 thứ 5 hàng tuần trên fanpage GoGi House để nhận thêm nhiều món qùa đặc biệt từ các khách mời bí ẩn mỗi tuần nhé!!!</p>",
      " 👉 Cơ hội lên đời đã đến, nhanh tay nhanh đũa chén GoGi – Trúng liền 1 tỷ ngay nhé !",
    ],
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
    rating: 1,
  },
  {
    id: "2",
    image: "https://inhat.vn/wp-content/uploads/2020/08/nh%C3%A0-h%C3%A0ng-%E1%BB%9F-t%C3%A2y-h%E1%BB%93-h%C3%A0-n%E1%BB%99i-6.jpg",
    banner: "https://inhat.vn/wp-content/uploads/2020/08/nh%C3%A0-h%C3%A0ng-%E1%BB%9F-t%C3%A2y-h%E1%BB%93-h%C3%A0-n%E1%BB%99i-6.jpg",
    title: "Golden Gate chính thức gia nhập biệt đội không lãng phí",
    content: [
      "<p>Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé: </p>",
      "<p> NHẬN NGAY VOUCHER 100K ÁP DỤNG CHO HÓA ĐƠN 400K NGAY KHI BẤM ĐỔI ƯU ĐÃI VỚI 0 G COINT</p>",
      "Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé:",
      "<p>🔶 Sử dụng ưu đãi tại GoGi và nhận ngay chiếc mã QR code kì diệu để tham gia quay thưởng với tổng giá trị tiền mặt 1 Tỷ Đồng trong vòng 10 tuần liên tiếp.</p>",
      "<p>🔶 Theo dõi và tham gia minigame trên livestream quay thưởng 1 Tỷ Đồng lúc 21:00 thứ 5 hàng tuần trên fanpage GoGi House để nhận thêm nhiều món qùa đặc biệt từ các khách mời bí ẩn mỗi tuần nhé!!!</p>",
      " 👉 Cơ hội lên đời đã đến, nhanh tay nhanh đũa chén GoGi – Trúng liền 1 tỷ ngay nhé !",
    ],
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
  },
  {
    id: "3",
    image: "https://toplistsaigon.com/wp-content/uploads/2019/09/nha-hang-do-nuong-o-sai-gon-9.jpg",
    banner: "https://inhat.vn/wp-content/uploads/2020/08/nh%C3%A0-h%C3%A0ng-%E1%BB%9F-t%C3%A2y-h%E1%BB%93-h%C3%A0-n%E1%BB%99i-6.jpg",
    title: "Golden Gate chính thức gia nhập biệt đội không lãng phí",
    content: [
      "<p>Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé: </p>",
      "<p> NHẬN NGAY VOUCHER 100K ÁP DỤNG CHO HÓA ĐƠN 400K NGAY KHI BẤM ĐỔI ƯU ĐÃI VỚI 0 G COINT</p>",
      "Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé:",
      "<p>🔶 Sử dụng ưu đãi tại GoGi và nhận ngay chiếc mã QR code kì diệu để tham gia quay thưởng với tổng giá trị tiền mặt 1 Tỷ Đồng trong vòng 10 tuần liên tiếp.</p>",
      "<p>🔶 Theo dõi và tham gia minigame trên livestream quay thưởng 1 Tỷ Đồng lúc 21:00 thứ 5 hàng tuần trên fanpage GoGi House để nhận thêm nhiều món qùa đặc biệt từ các khách mời bí ẩn mỗi tuần nhé!!!</p>",
      " 👉 Cơ hội lên đời đã đến, nhanh tay nhanh đũa chén GoGi – Trúng liền 1 tỷ ngay nhé !",
    ],
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
  },
  {
    id: "4",
    image: "https://toplistsaigon.com/wp-content/uploads/2019/09/nha-hang-do-nuong-o-sai-gon-9.jpg",
    banner: "https://inhat.vn/wp-content/uploads/2020/08/nh%C3%A0-h%C3%A0ng-%E1%BB%9F-t%C3%A2y-h%E1%BB%93-h%C3%A0-n%E1%BB%99i-6.jpg",
    title: "Golden Gate chính thức gia nhập biệt đội không lãng phí",
    content: [
      "<p>Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé: </p>",
      "<p> NHẬN NGAY VOUCHER 100K ÁP DỤNG CHO HÓA ĐƠN 400K NGAY KHI BẤM ĐỔI ƯU ĐÃI VỚI 0 G COINT</p>",
      "Ăn càng nhiều, cơ hội trở thành Tỷ Phú càng lớn. Tận hưởng ưu đãi và thịt nướng thơm ngon tại GoGi để nắm chắc cơ hội tham gia quay thưởng trúng 1 Tỷ Đồng bạn nhé:",
      "<p>🔶 Sử dụng ưu đãi tại GoGi và nhận ngay chiếc mã QR code kì diệu để tham gia quay thưởng với tổng giá trị tiền mặt 1 Tỷ Đồng trong vòng 10 tuần liên tiếp.</p>",
      "<p>🔶 Theo dõi và tham gia minigame trên livestream quay thưởng 1 Tỷ Đồng lúc 21:00 thứ 5 hàng tuần trên fanpage GoGi House để nhận thêm nhiều món qùa đặc biệt từ các khách mời bí ẩn mỗi tuần nhé!!!</p>",
      " 👉 Cơ hội lên đời đã đến, nhanh tay nhanh đũa chén GoGi – Trúng liền 1 tỷ ngay nhé !",
    ],
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
  },
];
