export const blogs = [
  {
    id: "1",
    image: "https://toplistsaigon.com/wp-content/uploads/2019/09/nha-hang-do-nuong-o-sai-gon-9.jpg",
    title: "Golden Gate chính thức gia nhập biệt đội không lãng phí",
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
    rating: 1,
  },
  {
    id: "2",
    image: "https://toplistsaigon.com/wp-content/uploads/2019/09/nha-hang-do-nuong-o-sai-gon-9.jpg",
    title: "Golden Gate chính thức gia nhập biệt đội không lãng phí",
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
  },
  {
    id: "3",
    image: "https://toplistsaigon.com/wp-content/uploads/2019/09/nha-hang-do-nuong-o-sai-gon-9.jpg",
    title: "Golden Gate chính thức gia nhập biệt đội không lãng phí",
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
  },
  {
    id: "4",
    image: "https://toplistsaigon.com/wp-content/uploads/2019/09/nha-hang-do-nuong-o-sai-gon-9.jpg",
    title: "Golden Gate chính thức gia nhập biệt đội không lãng phí",
    datePost: "01/12/2020",
    view: 100,
    like: 100,
    share: 100,
  },
];
