export const dummyPromoList = [
  {
    title: "Ăn Gogi trúng liền tay 1 tỷ",
    image: "https://ggg-api.s3.ap-southeast-1.amazonaws.com/promo1_8ff03668d9.jpg",
    location: "Hà Nội",
    timeAvailable: "01/12/2020 - 31/12/2020",
    voucher: 100,
    dateExpend: 10,
    description:
      "Hỡi các thực thần tứ phương, cùng lên đường thẳng tiến GoGi để có 100% CƠ HỘI nhận hàng ngàn quà tặng cùng giải thưởng tiền mặt trao tay tổng trị giá 1 TỶ ĐỒNG",
    listRestaurant: [
      {
        name: " Gogi House Trần Phú",
        address: "Hà Đông - 146 Trần Phú, Mỗ Lao, Hà Đông, Hà Nội",
        openClose: "10:30 AM - 11:00 PM",
        phone: "19006622",
        aboutKm: "0.7",
        map: {},
      },
    ],
    conditions: [
      " Mã code có hiệu lực sau 3 tiếng tính từ thời gian đăng ký",
      " Không áp dụng song song với ưu đãi khác",
      " Không có giá trị quy đổi thành tiền mặt hay ưu đãi khác",
      " Được áp dụng lũy kế (hóa đơn 1.000.000đ giảm 200.00đ, hóa đơn   2.000.000đ giảm 400.000đ,…)",
      " Khách hàng là thành viên The Golden Spoon được tích điểm nâng hạng   thẻ, không tích tiền vào ví, không sử dụng tiền và voucher trong ví",
    ],
  },
  {
    title: "Ăn Gogi trúng vàng 9999",
    image: "https://ggg-api.s3.ap-southeast-1.amazonaws.com/promo2_cfa4d1effa.jpg",
    location: "Hà Nội",
    timeAvailable: "01/12/2020 - 31/12/2020",
    voucher: 100,
    dateExpend: 10,
    description:
      "Hỡi các thực thần tứ phương, cùng lên đường thẳng tiến GoGi để có 100% CƠ HỘI nhận hàng ngàn quà tặng cùng giải thưởng tiền mặt trao tay tổng trị giá 1 TỶ ĐỒNG",
    listRestaurant: [
      {
        name: " Gogi House Trần Phú",
        address: "Hà Đông - 146 Trần Phú, Mỗ Lao, Hà Đông, Hà Nội",
        openClose: "10:30 AM - 11:00 PM",
        phone: "19006622",
        aboutKm: "0.7",
        map: {},
      },
    ],
    conditions: [
      " Mã code có hiệu lực sau 3 tiếng tính từ thời gian đăng ký",
      " Không áp dụng song song với ưu đãi khác",
      " Không có giá trị quy đổi thành tiền mặt hay ưu đãi khác",
      " Được áp dụng lũy kế (hóa đơn 1.000.000đ giảm 200.00đ, hóa đơn   2.000.000đ giảm 400.000đ,…)",
      " Khách hàng là thành viên The Golden Spoon được tích điểm nâng hạng   thẻ, không tích tiền vào ví, không sử dụng tiền và voucher trong ví",
    ],
  },
  {
    title: "Ăn Gogi trúng  1 tỷ",
    image: "https://ggg-api.s3.ap-southeast-1.amazonaws.com/promo1_mobile_de1bedf7da.jpg",
    location: "Hà Nội",
    timeAvailable: "01/12/2020 - 31/12/2020",
    voucher: 100,
    dateExpend: 10,
    description:
      "Hỡi các thực thần tứ phương, cùng lên đường thẳng tiến GoGi để có 100% CƠ HỘI nhận hàng ngàn quà tặng cùng giải thưởng tiền mặt trao tay tổng trị giá 1 TỶ ĐỒNG",
    listRestaurant: [
      {
        name: " Gogi House Trần Phú",
        address: "Hà Đông - 146 Trần Phú, Mỗ Lao, Hà Đông, Hà Nội",
        openClose: "10:30 AM - 11:00 PM",
        phone: "19006622",
        aboutKm: "0.7",
        map: {},
      },
      {
        name: " Gogi House Trần Phú",
        address: "Hà Đông - 146 Trần Phú, Mỗ Lao, Hà Đông, Hà Nội",
        openClose: "10:30 AM - 11:00 PM",
        phone: "19006622",
        aboutKm: "0.7",
        map: {},
      },
      {
        name: " Gogi House Trần Phú",
        address: "Hà Đông - 146 Trần Phú, Mỗ Lao, Hà Đông, Hà Nội",
        openClose: "10:30 AM - 11:00 PM",
        phone: "19006622",
        aboutKm: "0.7",
        map: {},
      },
      {
        name: " Gogi House Trần Phú",
        address: "Hà Đông - 146 Trần Phú, Mỗ Lao, Hà Đông, Hà Nội",
        openClose: "10:30 AM - 11:00 PM",
        phone: "19006622",
        aboutKm: "0.7",
        map: {},
      },
      {
        name: " Gogi House Trần Phú",
        address: "Hà Đông - 146 Trần Phú, Mỗ Lao, Hà Đông, Hà Nội",
        openClose: "10:30 AM - 11:00 PM",
        phone: "19006622",
        aboutKm: "0.7",
        map: {},
      },
    ],
    conditions: [
      " Mã code có hiệu lực sau 3 tiếng tính từ thời gian đăng ký",
      " Không áp dụng song song với ưu đãi khác",
      " Không có giá trị quy đổi thành tiền mặt hay ưu đãi khác",
      " Được áp dụng lũy kế (hóa đơn 1.000.000đ giảm 200.00đ, hóa đơn   2.000.000đ giảm 400.000đ,…)",
      " Khách hàng là thành viên The Golden Spoon được tích điểm nâng hạng   thẻ, không tích tiền vào ví, không sử dụng tiền và voucher trong ví",
    ],
  },
];
