export default [
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "119_232264_2021_02_08",
    amount: 350,
    validFrom: "2021-02-08T10:32:10+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Thanh toán tại nhà hàng The Coffee Inn Trường Chinh (HN-119)",
    date: "2021-02-08T10:32:10+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "Earned",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637436381434049297",
    amount: -50000,
    validFrom: "2020-12-15T14:09:03+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "TQ-Voucher tiền quy đổi 50.000đ",
    date: "2020-12-15T14:09:02+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637435898001795237",
    amount: -1,
    validFrom: "2020-12-15T00:43:20+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "20R21HT030_Hutong - Hành trình thưởng vị Hồng Kông",
    date: "2020-12-15T00:43:20+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637213632123095893",
    amount: -25000,
    validFrom: "2020-04-01T18:40:12+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "Flash sale 25k gcoin đổi 100k",
    date: "2020-04-01T18:49:23+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637207525260549110",
    amount: -25000,
    validFrom: "2020-03-25T17:02:06+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "Flash sale 25k gcoin đổi 100k",
    date: "2020-03-25T16:57:32+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637207375303616612",
    amount: -25000,
    validFrom: "2020-03-25T12:52:10+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "Flash sale 25k gcoin đổi 100k",
    date: "2020-03-25T12:48:40+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637207374449982040",
    amount: -11394,
    validFrom: "2020-03-25T12:50:45+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "Flash sale 25k gcoin đổi 100k",
    date: "2020-03-25T12:47:15+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637207340417950897",
    amount: -25000,
    validFrom: "2020-03-25T11:54:01+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "Flash sale 25k gcoin đổi 100k",
    date: "2020-03-25T11:50:47+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "340_200005_2020_03_05_11_25_02",
    amount: 16935,
    validFrom: "2020-03-05T11:25:02+07:00",
    expiryData: null,
    locationCode: "GG340",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Manwah Giga Mall Phạm Văn Đồng (HCM-340)",
    date: "2020-03-05T11:25:02+07:00",
    location: "Manwah Giga Mall Pham Van Dong (HCM - 340)",
    type: "Earned",
    restaurant: {
      code: 340,
      name: "Manwah Giga Mall Phạm Văn Đồng",
      internalName: null,
      address: "TTTM Giga Mall, 240 Phạm Văn Đồng, P. Hiệp Bình Chánh, Q. Thủ Đức, TPHCM",
      telephone: "02873007971",
      tel: "02873007971",
      stringeeNumber: "842873007971",
      latitude: 10.828553,
      longitude: 106.722266,
      regionName: "Ho Chi Minh",
      brandId: 27,
      brand: {
        id: "27",
        name: "Manwah",
        longName: "Manwah - Taiwanese Hot Pot",
        description:
          "Thực khách đến Manwah sẽ được tự mình khám phá hành trình ẩm thực đặc sắc với Buffet lẩu Đài Loan truyền thống đích thực. Nước lẩu ngọt vị tự nhiên, kết hợp hầm cùng các loại gia vị dậy mùi thơm đặc trưng; 68+ món nhúng kiểu đài và quầy buffet đồ uống, tráng miệng cao cấp chắc chắn sẽ làm hài lòng những thực khách khó tính nhất!",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Manwah-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/manwah-1200x818.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/manwah-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo48x48-07.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Manwah-3.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/manwah-1.png",
        concept: {
          id: 6,
          name: "HOTPOT",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/hotpot.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/hotpot-active.png",
          order: 6,
        },
        conceptId: 6,
      },
      zone: "HCM",
      sbu: "HCM",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/manwah.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/manwah.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/manwah.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 7,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "337_200001_2020_03_05_10_37_34",
    amount: 1625,
    validFrom: "2020-03-05T10:37:34+07:00",
    expiryData: null,
    locationCode: "GG337",
    memberNo: null,
    description: "Thanh toán tại nhà hàng SumoBBQ Giga Mall Phạm Văn Đồng (HCM-337)",
    date: "2020-03-05T10:37:34+07:00",
    location: "SumoBBQ Giga Mall Phạm Văn Đồng (HCM - 337)",
    type: "Earned",
    restaurant: {
      code: 337,
      name: "Sumo Yakiniku Giga Mall Phạm Văn Đồng",
      internalName: null,
      address: "TTTM Giga Mall, 240 Phạm Văn Đồng, P. Hiệp Bình Chánh, Q.Thủ Đức, Tp.HCM",
      telephone: "02873007987",
      tel: "02873007987",
      stringeeNumber: "842873007987",
      latitude: 10.828553,
      longitude: 106.722236,
      regionName: "Ho Chi Minh",
      brandId: 3,
      brand: {
        id: "3",
        name: "Sumo Yakiniku",
        longName: "Sumo Yakiniku - Nhà hàng thịt nướng Nhật Bản",
        description:
          "Gắn liền với tên gọi của nghệ thuật nướng nổi tiếng Nhật Bản, Sumo Yakiniku là nhà hàng thịt nướng chú trọng đến nguyên liệu thượng hạng hay quá trình chuẩn bị tinh tế công phu từ bảo quản, chế biến thịt, sốt ướp, sốt chấm và kỹ thuật nướng. Với Menu gọi món của Sumo, thực khách sẽ được thưởng thức trọn vẹn mỹ vị Nhật bản: từ các loại thịt cao cấp với bò Wagyu, Harami, thăn ngoại bò Mỹ, heo Iberico cho tới các loại lẩu và món ăn kèm đặc sắc. Bên cạnh đó, Sumo Yakiniku còn phục vụ menu Buffet dành cho khách hàng muốn tận hưởng thoả thích thịt nướng Nhật Bản. Với Sumo Yakiniku mỗi bữa tiệc nướng đều là một hành trình khám phá thú vị hội tụ tinh hoa ẩm thực xứ Phù Tang!",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Sumo-3.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/sumo.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/sumo-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: false,
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Sumo-2.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/jack.png",
        concept: {
          id: 2,
          name: "BBQ",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/bbq.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/bbq-active.png",
          order: 2,
        },
        conceptId: 2,
      },
      zone: "HCM",
      sbu: "HCM",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Sumo_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Sumo_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/sumo.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 7,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637189996184529235",
    amount: -24231,
    validFrom: "2020-03-05T10:06:58+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "GPeople Cash Voucher",
    date: "2020-03-05T10:06:58+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "139_173106_2020_01_01_15_56_13",
    amount: 550,
    validFrom: "2020-01-01T15:56:13+07:00",
    expiryData: null,
    locationCode: "GG139",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Daruma Vincom Nguyen Chi Thanh (HN-139)",
    date: "2020-01-01T15:56:13+07:00",
    location: "Daruma Vincom Nguyen Chi Thanh (HN - 139)",
    type: "Earned",
    restaurant: {
      code: 139,
      name: "Daruma Vincom Nguyễn Chí Thanh",
      internalName: null,
      address: "Tầng 5, TTTM Vincom 54 Nguyễn Chí Thanh, Láng Thượng, Đống Đa, Hà Nội",
      telephone: "02473007331",
      tel: "02473007331",
      stringeeNumber: "842473007331",
      latitude: 21.023611718,
      longitude: 105.809124,
      regionName: "Ha Noi",
      brandId: 9,
      brand: {
        id: "9",
        name: "Daruma",
        longName: "Daruma - Món ngon Nhật Bản mỗi ngày",
        description:
          "Daruma mang đến cho khách hàng những trải nghiệm ẩm thực Nhật Bản thân thiện, gần gũi với thực đơn gọi món và Buffet Lẩu mang đậm văn hóa của xứ sở hoa anh đào.\r\n\r\nTại Daruma, bạn sẽ luôn được thưởng thức các món ăn chuẩn hương vị Nhật, từ các lựa chọn đa dạng các loại Buffet đến các món Sushi, Sashimi tươi ngon bổ dưỡng cho tới các set mỳ, cơm đa dạng chỉ từ 69.000VNĐ.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-5.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x-794x900.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo-đen-trắng-2020.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Untitled-design-2-01.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-1.png",
        concept: {
          id: 3,
          name: "JAPANESE",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese-active.png",
          order: 3,
        },
        conceptId: 3,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Daruma_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Daruma_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/daruma.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "139_173073_2020_01_01_11_05_52",
    amount: 15595,
    validFrom: "2020-01-01T11:05:52+07:00",
    expiryData: null,
    locationCode: "GG139",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Daruma Vincom Nguyen Chi Thanh (HN-139)",
    date: "2020-01-01T11:05:52+07:00",
    location: "Daruma Vincom Nguyen Chi Thanh (HN - 139)",
    type: "Earned",
    restaurant: {
      code: 139,
      name: "Daruma Vincom Nguyễn Chí Thanh",
      internalName: null,
      address: "Tầng 5, TTTM Vincom 54 Nguyễn Chí Thanh, Láng Thượng, Đống Đa, Hà Nội",
      telephone: "02473007331",
      tel: "02473007331",
      stringeeNumber: "842473007331",
      latitude: 21.023611718,
      longitude: 105.809124,
      regionName: "Ha Noi",
      brandId: 9,
      brand: {
        id: "9",
        name: "Daruma",
        longName: "Daruma - Món ngon Nhật Bản mỗi ngày",
        description:
          "Daruma mang đến cho khách hàng những trải nghiệm ẩm thực Nhật Bản thân thiện, gần gũi với thực đơn gọi món và Buffet Lẩu mang đậm văn hóa của xứ sở hoa anh đào.\r\n\r\nTại Daruma, bạn sẽ luôn được thưởng thức các món ăn chuẩn hương vị Nhật, từ các lựa chọn đa dạng các loại Buffet đến các món Sushi, Sashimi tươi ngon bổ dưỡng cho tới các set mỳ, cơm đa dạng chỉ từ 69.000VNĐ.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-5.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x-794x900.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo-đen-trắng-2020.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Untitled-design-2-01.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-1.png",
        concept: {
          id: 3,
          name: "JAPANESE",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese-active.png",
          order: 3,
        },
        conceptId: 3,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Daruma_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Daruma_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/daruma.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "139_173070_2020_01_01_10_33_11",
    amount: 13945,
    validFrom: "2020-01-01T10:33:11+07:00",
    expiryData: null,
    locationCode: "GG139",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Daruma Vincom Nguyen Chi Thanh (HN-139)",
    date: "2020-01-01T10:33:11+07:00",
    location: "Daruma Vincom Nguyen Chi Thanh (HN - 139)",
    type: "Earned",
    restaurant: {
      code: 139,
      name: "Daruma Vincom Nguyễn Chí Thanh",
      internalName: null,
      address: "Tầng 5, TTTM Vincom 54 Nguyễn Chí Thanh, Láng Thượng, Đống Đa, Hà Nội",
      telephone: "02473007331",
      tel: "02473007331",
      stringeeNumber: "842473007331",
      latitude: 21.023611718,
      longitude: 105.809124,
      regionName: "Ha Noi",
      brandId: 9,
      brand: {
        id: "9",
        name: "Daruma",
        longName: "Daruma - Món ngon Nhật Bản mỗi ngày",
        description:
          "Daruma mang đến cho khách hàng những trải nghiệm ẩm thực Nhật Bản thân thiện, gần gũi với thực đơn gọi món và Buffet Lẩu mang đậm văn hóa của xứ sở hoa anh đào.\r\n\r\nTại Daruma, bạn sẽ luôn được thưởng thức các món ăn chuẩn hương vị Nhật, từ các lựa chọn đa dạng các loại Buffet đến các món Sushi, Sashimi tươi ngon bổ dưỡng cho tới các set mỳ, cơm đa dạng chỉ từ 69.000VNĐ.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-5.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x-794x900.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo-đen-trắng-2020.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Untitled-design-2-01.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-1.png",
        concept: {
          id: 3,
          name: "JAPANESE",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese-active.png",
          order: 3,
        },
        conceptId: 3,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Daruma_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Daruma_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/daruma.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "139_173069_2020_01_01_10_28_38",
    amount: 9545,
    validFrom: "2020-01-01T10:28:38+07:00",
    expiryData: null,
    locationCode: "GG139",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Daruma Vincom Nguyen Chi Thanh (HN-139)",
    date: "2020-01-01T10:28:38+07:00",
    location: "Daruma Vincom Nguyen Chi Thanh (HN - 139)",
    type: "Earned",
    restaurant: {
      code: 139,
      name: "Daruma Vincom Nguyễn Chí Thanh",
      internalName: null,
      address: "Tầng 5, TTTM Vincom 54 Nguyễn Chí Thanh, Láng Thượng, Đống Đa, Hà Nội",
      telephone: "02473007331",
      tel: "02473007331",
      stringeeNumber: "842473007331",
      latitude: 21.023611718,
      longitude: 105.809124,
      regionName: "Ha Noi",
      brandId: 9,
      brand: {
        id: "9",
        name: "Daruma",
        longName: "Daruma - Món ngon Nhật Bản mỗi ngày",
        description:
          "Daruma mang đến cho khách hàng những trải nghiệm ẩm thực Nhật Bản thân thiện, gần gũi với thực đơn gọi món và Buffet Lẩu mang đậm văn hóa của xứ sở hoa anh đào.\r\n\r\nTại Daruma, bạn sẽ luôn được thưởng thức các món ăn chuẩn hương vị Nhật, từ các lựa chọn đa dạng các loại Buffet đến các món Sushi, Sashimi tươi ngon bổ dưỡng cho tới các set mỳ, cơm đa dạng chỉ từ 69.000VNĐ.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-5.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x-794x900.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo-đen-trắng-2020.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Untitled-design-2-01.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-1.png",
        concept: {
          id: 3,
          name: "JAPANESE",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese-active.png",
          order: 3,
        },
        conceptId: 3,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Daruma_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Daruma_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/daruma.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "139_173068_2020_01_01_10_20_27",
    amount: 30720,
    validFrom: "2020-01-01T10:20:27+07:00",
    expiryData: null,
    locationCode: "GG139",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Daruma Vincom Nguyen Chi Thanh (HN-139)",
    date: "2020-01-01T10:20:27+07:00",
    location: "Daruma Vincom Nguyen Chi Thanh (HN - 139)",
    type: "Earned",
    restaurant: {
      code: 139,
      name: "Daruma Vincom Nguyễn Chí Thanh",
      internalName: null,
      address: "Tầng 5, TTTM Vincom 54 Nguyễn Chí Thanh, Láng Thượng, Đống Đa, Hà Nội",
      telephone: "02473007331",
      tel: "02473007331",
      stringeeNumber: "842473007331",
      latitude: 21.023611718,
      longitude: 105.809124,
      regionName: "Ha Noi",
      brandId: 9,
      brand: {
        id: "9",
        name: "Daruma",
        longName: "Daruma - Món ngon Nhật Bản mỗi ngày",
        description:
          "Daruma mang đến cho khách hàng những trải nghiệm ẩm thực Nhật Bản thân thiện, gần gũi với thực đơn gọi món và Buffet Lẩu mang đậm văn hóa của xứ sở hoa anh đào.\r\n\r\nTại Daruma, bạn sẽ luôn được thưởng thức các món ăn chuẩn hương vị Nhật, từ các lựa chọn đa dạng các loại Buffet đến các món Sushi, Sashimi tươi ngon bổ dưỡng cho tới các set mỳ, cơm đa dạng chỉ từ 69.000VNĐ.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-5.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x-794x900.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo-đen-trắng-2020.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Artboard-96@10x.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Untitled-design-2-01.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Daruma-1.png",
        concept: {
          id: 3,
          name: "JAPANESE",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese-active.png",
          order: 3,
        },
        conceptId: 3,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Daruma_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Daruma_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/daruma.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "156_127648_2020_01_01_07_40_53",
    amount: 5749,
    validFrom: "2020-01-01T07:40:53+07:00",
    expiryData: null,
    locationCode: "GG156",
    memberNo: null,
    description: "Thanh toán tại nhà hàng ICook Nguyen Thai Hoc (HN-156)",
    date: "2020-01-01T07:40:53+07:00",
    location: "ICook Nguyen Thai Hoc (HN - 156)",
    type: "Earned",
    restaurant: {
      code: 156,
      name: "iCOOK",
      internalName: null,
      address: "Số 5 ngõ 71/30 Hoàng Văn Thái , Khương Trung, Thanh Xuân, Hà Nội",
      telephone: "0964643860",
      tel: "0964643860",
      stringeeNumber: "0",
      latitude: 20.995737,
      longitude: 105.826006,
      regionName: "Ha Noi",
      brandId: 17,
      brand: {
        id: "17",
        name: "iCook",
        longName: "iCook",
        description:
          "iCook – Restaurant at Home mang đến giải pháp cho những bà nội trợ “đảm đang nhưng ít có thời gian thể hiện”. Vị thơm ngon của lẩu Thái Kichi Kichi, lẩu nấm Ashima hay thịt nướng SumoBBQ cuối cùng đã có thể tỏa hương ngay trong căn bếp nhà bạn mà không tốn thời gian đi chợ, chọn lựa, nấu nướng mà chỉ cần vài thao tác đặt hàng và 15 phút chuẩn bị nhanh gọn.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Icook-4.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/500x500.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo-TGS.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/500x500.png",
        tgsType: 2,
        tgsExternalLink: "https://icook.com.vn",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Logo-brand-03.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/icook-1.png",
        concept: {
          id: 2,
          name: "BBQ",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/bbq.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/bbq-active.png",
          order: 2,
        },
        conceptId: 2,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/icook.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/icook.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/icook.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "a3c4fd20-81ba-4304-bcba-5688eaaf1786",
    amount: 200000,
    validFrom: "2020-01-01T07:05:17+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: null,
    date: "2020-01-01T07:05:17+07:00",
    location: "HQ",
    type: "Earned",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "156_127646_2020_01_01_07_02_46",
    amount: 17499,
    validFrom: "2020-01-01T07:02:46+07:00",
    expiryData: null,
    locationCode: "GG156",
    memberNo: null,
    description: "Thanh toán tại nhà hàng ICook Nguyen Thai Hoc (HN-156)",
    date: "2020-01-01T07:02:46+07:00",
    location: "ICook Nguyen Thai Hoc (HN - 156)",
    type: "Earned",
    restaurant: {
      code: 156,
      name: "iCOOK",
      internalName: null,
      address: "Số 5 ngõ 71/30 Hoàng Văn Thái , Khương Trung, Thanh Xuân, Hà Nội",
      telephone: "0964643860",
      tel: "0964643860",
      stringeeNumber: "0",
      latitude: 20.995737,
      longitude: 105.826006,
      regionName: "Ha Noi",
      brandId: 17,
      brand: {
        id: "17",
        name: "iCook",
        longName: "iCook",
        description:
          "iCook – Restaurant at Home mang đến giải pháp cho những bà nội trợ “đảm đang nhưng ít có thời gian thể hiện”. Vị thơm ngon của lẩu Thái Kichi Kichi, lẩu nấm Ashima hay thịt nướng SumoBBQ cuối cùng đã có thể tỏa hương ngay trong căn bếp nhà bạn mà không tốn thời gian đi chợ, chọn lựa, nấu nướng mà chỉ cần vài thao tác đặt hàng và 15 phút chuẩn bị nhanh gọn.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Icook-4.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/500x500.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo-TGS.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/500x500.png",
        tgsType: 2,
        tgsExternalLink: "https://icook.com.vn",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Logo-brand-03.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/icook-1.png",
        concept: {
          id: 2,
          name: "BBQ",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/bbq.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/bbq-active.png",
          order: 2,
        },
        conceptId: 2,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/icook.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/icook.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/icook.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637123616256719206",
    amount: -1000,
    validFrom: "2019-12-19T14:13:45+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: null,
    date: "2019-12-19T14:15:12+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637123615476062777",
    amount: -1000,
    validFrom: "2019-12-19T14:12:27+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: null,
    date: "2019-12-19T14:14:44+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637123616749233748",
    amount: -1000,
    validFrom: "2019-12-19T14:14:34+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: null,
    date: "2019-12-19T14:14:33+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "637088604537805001",
    amount: -1641,
    validFrom: "2019-11-09T01:40:53+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: null,
    date: "2019-11-09T01:39:43+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "319_100015_2019_10_09_09_31_27",
    amount: 24695,
    validFrom: "2019-10-09T09:31:27+07:00",
    expiryData: null,
    locationCode: "GG319",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Isushi Thái Hà (HN-319)",
    date: "2019-10-09T09:31:27+07:00",
    location: "iSushi Thái Hà (HN-319)",
    type: "Earned",
    restaurant: {
      code: 319,
      name: "iSushi Thái Hà",
      internalName: null,
      address: "Tầng 2 TTTM Parkson cũ, số 1 Thái Hà, Quận Đống Đa, Hà Nội",
      telephone: "02473007673",
      tel: "02473007673",
      stringeeNumber: "842473007673",
      latitude: 21.009311,
      longitude: 105.823777,
      regionName: "Ha Noi",
      brandId: 6,
      brand: {
        id: "6",
        name: "iSushi",
        longName: "iSushi - Buffet Sashimi tươi ngon thỏa thích",
        description:
          "Là nhà hàng buffet sashimi duy nhất trên thị trường, với đội ngũ đầu bếp tâm huyết, iSushi mang đến thực khách cơ hội trải nghiệm buffet sashimi tươi ngon thoả thích và hơn 100 món Nhật tinh hoa trong không gian chuẩn Nhật. Thực khách có thể lựa chọn Buffet Sakura với 439,000đ hoặc Buffet Kiku để thưởng thức thêm các món nướng BBQ với 499,000đ.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Isushi-3.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo48x48-02.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi-2.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi-1.png",
        concept: {
          id: 3,
          name: "JAPANESE",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese-active.png",
          order: 3,
        },
        conceptId: 3,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/iSushi_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/iSushi_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/isushi.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "1_100008_2019_10_08_17_29_10",
    amount: 4595,
    validFrom: "2019-10-08T17:29:10+07:00",
    expiryData: null,
    locationCode: "GG319",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Isushi Thái Hà (HN-319)",
    date: "2019-10-08T17:29:10+07:00",
    location: "iSushi Thái Hà (HN-319)",
    type: "Earned",
    restaurant: {
      code: 319,
      name: "iSushi Thái Hà",
      internalName: null,
      address: "Tầng 2 TTTM Parkson cũ, số 1 Thái Hà, Quận Đống Đa, Hà Nội",
      telephone: "02473007673",
      tel: "02473007673",
      stringeeNumber: "842473007673",
      latitude: 21.009311,
      longitude: 105.823777,
      regionName: "Ha Noi",
      brandId: 6,
      brand: {
        id: "6",
        name: "iSushi",
        longName: "iSushi - Buffet Sashimi tươi ngon thỏa thích",
        description:
          "Là nhà hàng buffet sashimi duy nhất trên thị trường, với đội ngũ đầu bếp tâm huyết, iSushi mang đến thực khách cơ hội trải nghiệm buffet sashimi tươi ngon thoả thích và hơn 100 món Nhật tinh hoa trong không gian chuẩn Nhật. Thực khách có thể lựa chọn Buffet Sakura với 439,000đ hoặc Buffet Kiku để thưởng thức thêm các món nướng BBQ với 499,000đ.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/Isushi-3.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/logo48x48-02.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi-2.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/isushi-1.png",
        concept: {
          id: 3,
          name: "JAPANESE",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/japanese-active.png",
          order: 3,
        },
        conceptId: 3,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/iSushi_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/iSushi_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/isushi.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 228,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "636881238029906009",
    amount: -50000,
    validFrom: "2019-03-14T01:30:03+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "GPeople Cash Voucher",
    date: "2019-03-14T01:30:01+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "636876951286608034",
    amount: -950000,
    validFrom: "2019-03-09T02:25:28+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "GPeople Cash Voucher",
    date: "2019-03-08T18:30:00+07:00",
    location: "HQ",
    type: "Used",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "119_100222_2019_02_14_05_05_36",
    amount: 159736,
    validFrom: "2019-03-07T05:05:36+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Canteen Truong Chinh (HN - 119)",
    date: "2019-03-07T05:05:36+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "Earned",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "4340a81f-356f-4a8c-953a-92b16a2c4bf1",
    amount: -813655,
    validFrom: "2019-03-07T05:05:32+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Transfer to membership GPG0000000000001VN",
    date: "2019-03-07T05:05:30+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "TransferOut",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "07fc696e-1b1f-4f04-8f0d-0e9ea061a261",
    amount: 813655,
    validFrom: "2019-03-07T05:05:32+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Transfer from membership 2454874001",
    date: "2019-03-07T05:05:30+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "TransferIn",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "119_100222_2019_02_14_05_02_48",
    amount: 159736,
    validFrom: "2019-03-07T00:00:00+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Canteen Truong Chinh (HN - 119)",
    date: "2019-03-07T05:05:00+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "Earned",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "119_100222_2019_02_14_05_05_25",
    amount: 159736,
    validFrom: "2019-03-07T00:00:00+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Canteen Truong Chinh (HN - 119)",
    date: "2019-03-07T05:05:00+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "Earned",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "119_100222_2019_02_14_05_05_16",
    amount: 159736,
    validFrom: "2019-03-07T05:05:17+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Canteen Truong Chinh (HN - 119)",
    date: "2019-03-07T05:05:17+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "Earned",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "119_100222_2019_02_14_05_05_06",
    amount: 159736,
    validFrom: "2019-03-07T05:05:06+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Canteen Truong Chinh (HN - 119)",
    date: "2019-03-07T05:05:06+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "Earned",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "119_100222_2019_02_14_05_04_19",
    amount: 159736,
    validFrom: "2019-03-07T05:04:19+07:00",
    expiryData: null,
    locationCode: "GG119",
    memberNo: null,
    description: "Thanh toán tại nhà hàng Canteen Truong Chinh (HN - 119)",
    date: "2019-03-07T05:04:19+07:00",
    location: "The Coffee Inn Trường Chinh (HN-119)",
    type: "Earned",
    restaurant: {
      code: 119,
      name: "The Coffee Inn Trường Chinh",
      internalName: null,
      address: "Tầng 6, 315 Trường Chinh,Thanh Xuân, Hà Nội",
      telephone: "02473006618",
      tel: "02473006618",
      stringeeNumber: "0",
      latitude: 21.002288,
      longitude: 105.82283,
      regionName: "Ha Noi",
      brandId: 28,
      brand: {
        id: "28",
        name: "The Coffee Inn",
        longName: "The Coffee Inn – Pure In Every Drop",
        description:
          "The Coffee Inn là sự kết hợp hoàn hảo giữa nguyên liệu cao cấp từ những vùng trồng cà phê đặc sản nổi tiếng tại Việt Nam (Sơn La, Khe Sanh, Đà Lạt) cùng kĩ thuật rang xay từ Nhật Bản đảm bảo cho những tách café chất lượng và thuần khiết nhất.",
        logo: null,
        smallLogoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI-266.png",
        lastUpdate: null,
        logoUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square.png",
        tagSearch: null,
        logoBW: null,
        logoBWUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-bw.png",
        isHidden: 0,
        order: null,
        logoSingleColor: null,
        logoSingleColorUrl: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn-square-sc.png",
        tgsType: 1,
        tgsExternalLink: "",
        backgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/the-coffee-inn.png",
        headerBackgroundBanner: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/06/TCI.png",
        concept: {
          id: 7,
          name: "KHÁC",
          icon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others.png",
          activeIcon: "http://tgscms.ggg.com.vn/wp-content/uploads/2020/04/others-active.png",
          order: 7,
        },
        conceptId: 7,
      },
      zone: "HN",
      sbu: "HN",
      isActive: 1,
      isFranchise: null,
      thumbnail: "restaurants/Canteen_MB.jpg",
      thumbnailUrl: "http://booking.ggg.com.vn/resources/restaurants/Canteen_MB.jpg",
      logo: "http://booking.ggg.com.vn/resources/logo-brand/the-coffee-inn-square.png",
      openTime: "09:00:00",
      closeTime: "22:00:00",
      districtId: 247,
      district: null,
      province: null,
      distance: null,
      email: null,
    },
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "Haravan_order_id_2019_02_23",
    amount: 28250,
    validFrom: "2018-12-15T16:39:34+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: "",
    date: "2018-12-15T16:39:34+07:00",
    location: "HQ",
    type: "Earned",
    restaurant: null,
    currency: "Point",
  },
  {
    pointType: "Point",
    rewardDate: null,
    receiptNumber: "BB404621-E3C2-421A-A1C0-E46C2B5131FF",
    amount: 14975,
    validFrom: "2016-08-22T00:00:00+07:00",
    expiryData: null,
    locationCode: "GG1",
    memberNo: null,
    description: null,
    date: "2016-08-22T00:00:00+07:00",
    location: "HQ",
    type: "Earned",
    restaurant: null,
    currency: "Point",
  },
];
