export const DEVELOPMENT_MODE = "develop";
export const PRODUCTION_MODE = "production";
export const JWT_TOKEN = "jwtToken";

/**
 * REDUCER
 */

export const SELECTED_SECTION = "SELECTED_SECTION";
export const SELECTED_COMPONENT = "SELECTED_COMPONENT";
export const CONFIG = "CONFIG";
export const SHOW_LANGUAGE_LOCATION = "SHOW_LANGUAGE_LOCATION";
export const SET_FIRST_LOAD = "SET_FIRST_LOAD";
export const SET_LAT_LNG = "SET_LAT_LNG";
/**
 * UPDATE REDUCER
 */

export const SET_MODE = "SET_MODE";
export const SET_SELECTED_SECTION = "SET_SELECTED_SECTION";
export const SET_SELECTED_COMPONENT = "SET_SELECTED_COMPONENT";
export const SET_CONFIG = "SET_CONFIG";
export const SET_MODIFIED_CONFIG = "SET_MODIFIED_CONFIG";
export const UPDATE_CONFIG = "UPDATE_CONFIG";
export const REMOVE_CONFIG = "REMOVE_CONFIG";
export const SET_TOKEN = "SET_TOKEN";
export const SET_SITE = "SET_SITE";
export const SET_INITIAL_SITE = "SET_INITIAL_SITE";
export const ADD_SECTION = "ADD_SECTION";
export const REMOVE_SECTION = "REMOVE_SECTION";
export const SET_MEDIAS = "SET_MEDIAS";
export const SET_MEDIA_COUNT = "SET_MEDIA_COUNT";
export const ADD_FILES_UPLOAD = "ADD_FILES_UPLOAD";
export const REMOVE_FILES_UPLOAD = "REMOVE_FILES_UPLOAD";
export const SET_MEDIA_DIALOG = "SET_MEDIA_DIALOG";
export const SET_SHOW_MENU_HEADER = "SET_SHOW_MENU_HEADER";
export const SET_SHOW_FOOTER = "SET_SHOW_FOOTER";
export const SET_HEIGHT_POPUP = "SET_HEIGHT_POPUP";

export const UPDATE_API_STATUS = "UPDATE_API_STATUS";
export const SET_LOCALE = "SET_LOCALE";
export const SET_LOCATION = "SET_LOCATION";
export const SET_PAGE_NAME = "SET_PAGE_NAME";
export const SET_OUR_MENUS = "SET_OUR_MENUS";
export const SET_HEADER_HEIGHT = "SET_HEADER_HEIGHT";
export const SET_HOST = "SET_HOST";
export const SET_BLOG_SLUG = "SET_BLOG_SLUG";
export const ACCEPT_COOKIE = "ACCEPT_COOKIE";
export const SET_LIST_PROMO_ACTIVE = "SET_LIST_PROMO_ACTIVE";
export const SET_LIST_BOOKING = "SET_LIST_BOOKING";
export const ADD_DYNAMIC_BLOCK = "ADD_DYNAMIC_BLOCK";
export const REMOVE_DYNAMIC_BLOCK = "REMOVE_DYNAMIC_BLOCK";
export const UPDATE_TITLE_BLOCK = "UPDATE_TITLE_BLOCK";
export const UPDATE_phoneOTP = "UPDATE_phoneOTP";
export const UPDATE_VALUE_TRANSITION = "UPDATE_VALUE_TRANSITION";
export const SET_GOOGLE_MAP_API = "SET_GOOGLE_MAP_API";
// NOTIFICATION

export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";

export const SET_USER_INFO = "SET_USER_INFO";
export const GET_INFO_USER = "GET_INFO_USER";
export const SET_TOKEN_USER = "SET_TOKEN_USER";
export const SHOW_LIST_BRAND = "SHOW_LIST_BRAND";
export const GET_MY_VOUCHER = "GET_MY_VOUCHER";
/**
 * SAGA
 */

export const FETCH_CONFIG = "FETCH_CONFIG";
export const PUT_CONFIG = "PUT_CONFIG";
export const PUT_PUBLIC_CONFIG = "PUT_PUBLIC_CONFIG";
export const FETCH_MEDIAS = "FETCH_MEDIAS";
export const FETCH_MEDIA_COUNT = "FETCH_MEDIA_COUNT";
export const UPLOAD_FILES = "UPLOAD_FILES";
export const DOWNLOAD_FILE = "DOWNLOAD_FILE";
export const LOGIN = "LOGIN";
export const GET_SITE = "GET_SITE";
export const SET_SITE_CODE = "SET_SITE_CODE";
export const FETCH_MENU = "FETCH_MENU";

export const SUBMIT_OPT = "SUBMIT_OTP";
export const SUBMIT_PHONE = "SUBMIT_PHONE";

export const GET_BLOGS_BY_IS_SHOW = "GET_BLOGS_BY_IS_SHOW";
export const SET_LIST_BLOG_IS_SHOW = "SET_LIST_BLOG_IS_SHOW";
export const SET_PREVIEW_MODE = "SET_PREVIEW_MODE";
export const SET_LIST_BLOG_EDIT_PAGE = "SET_LIST_BLOG_EDIT_PAGE";
export const SET_LIST_PROMO_EDIT_PAGE = "SET_LIST_PROMO_EDIT_PAGE";

export const SET_PROMO_OF_USER = "SET_PROMO_OF_USER";
export const GET_PROMO_OF_USER = "GET_PROMO_OF_USER";

export const SET_ICON_VIEW_MAP = "SET_ICON_VIEW_MAP";

export const GET_TRANSACTION = "GET_TRANSACTION";
export const SET_TRANSACTION = "SET_TRANSACTION";

export const SET_LIST_PROVINCE = "SET_LIST_PROVINCE";
export const SET_PROVINCE_SELECTED = "SET_PROVINCE_SELECTED";
export const SET_NUM_PROMO = "SET_NUM_PROMO";

export const PROMO_FLASH_SALE = "limited-gift-promotion";
export const PROMO_NORMAL = "gift-promotion";

export const SET_DISABLE_SCROLL_TAB_BANNER = "SET_DISABLE_SCROLL_TAB_BANNER";

export const SET_DATA_INITIAL = "SET_DATA_INITIAL";
